// app/layout.tsx
import React, { ReactNode } from 'react';

interface RootLayoutProps {
  children: ReactNode;
}

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
};

const RootLayout: React.FC<RootLayoutProps> = ({ children }) => {
  return (
    <html lang="en">
      <body>
          {children}
      </body>
    </html>
  );
};

export default RootLayout;
