// app/layout.tsx
import React, { ReactNode } from 'react';
<<<<<<< HEAD
import { ThemeProvider } from './ContextTheme/theme-provider'; // Adjust the path if necessary
=======
>>>>>>> main

interface RootLayoutProps {
  children: ReactNode;
}

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
};

const RootLayout: React.FC<RootLayoutProps> = ({ children }) => {
  return (
    <html lang="en">
<<<<<<< HEAD
      <ThemeProvider>
        <body>
          {children}
        </body>
      </ThemeProvider>
=======
      <body>
          {children}
      </body>
>>>>>>> main
    </html>
  );
};

export default RootLayout;
