// app/layout.tsx
import React, { ReactNode } from 'react';
import { ThemeProvider } from './ContextTheme/theme-provider'; // Adjust the path if necessary

interface RootLayoutProps {
  children: ReactNode;
}

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
};

const RootLayout: React.FC<RootLayoutProps> = ({ children }) => {
  return (
    <html lang="en">
      <ThemeProvider>
        <body>
          {children}
        </body>
      </ThemeProvider>
    </html>
  );
};

export default RootLayout;
